<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace fabula\condition;

use \php\Boot;
use \haxe\Exception;

/**
 * Base class to test a condition
 * @author Loudo
 */
class Condition {
	/**
	 * @var bool
	 */
	public $_affirmation;
	/**
	 * @var mixed
	 */
	public $condition;
	/**
	 * @var EConditionType
	 */
	public $type;

	/**
	 * @param mixed $condition
	 * @param EConditionType $type
	 * @param bool $affirmation
	 * 
	 * @return void
	 */
	public function __construct ($condition, $type, $affirmation = true) {
		#C:\HaxeLib\fabula/git/src/fabula/condition/Condition.hx:15: lines 15-19
		if ($affirmation === null) {
			$affirmation = true;
		}
		#C:\HaxeLib\fabula/git/src/fabula/condition/Condition.hx:16: characters 3-29
		$this->condition = $condition;
		#C:\HaxeLib\fabula/git/src/fabula/condition/Condition.hx:17: characters 3-19
		$this->type = $type;
		#C:\HaxeLib\fabula/git/src/fabula/condition/Condition.hx:18: characters 3-29
		$this->_affirmation = $affirmation;
	}

	/**
	 * @return bool
	 */
	public function test () {
		#C:\HaxeLib\fabula/git/src/fabula/condition/Condition.hx:23: characters 3-8
		throw Exception::thrown("[Condition] Override test function");
	}
}

Boot::registerClass(Condition::class, 'fabula.condition.Condition');
