<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace fabula\condition;

use \php\Boot;
use \php\_Boot\HxString;

class VariableString extends Variable {
	/**
	 * @param string $id
	 * @param string $startingValue
	 * 
	 * @return void
	 */
	public function __construct ($id, $startingValue) {
		#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:9: characters 3-35
		parent::__construct($id, EVariableType::STRING(), $startingValue);
	}

	/**
	 * @param string $operation
	 * @param string $targetValue
	 * 
	 * @return bool
	 */
	public function compare ($operation, $targetValue) {
		#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:28: lines 28-38
		if ($operation === "!=") {
			#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:33: characters 5-32
			return $this->value !== $targetValue;
		} else if ($operation === "=") {
			#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:31: characters 5-32
			return $this->value === $targetValue;
		} else if ($operation === "in") {
			#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:35: characters 5-44
			return HxString::indexOf($this->value, $targetValue) !== -1;
		} else {
			#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:37: characters 5-17
			return false;
		}
	}

	/**
	 * @param string $value
	 * 
	 * @return string
	 */
	public function convert ($value) {
		#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:23: characters 3-15
		return $value;
	}

	/**
	 * @param string $value
	 * 
	 * @return bool
	 */
	public function set ($value) {
		#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:14: characters 3-32
		$temp = $this->value;
		#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:15: characters 3-21
		$this->value = $value;
		#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:16: lines 16-17
		if ($temp !== $this->value) {
			#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:17: characters 4-15
			return true;
		}
		#C:\HaxeLib\fabula/git/src/fabula/condition/VariableString.hx:18: characters 3-15
		return false;
	}
}

Boot::registerClass(VariableString::class, 'fabula.condition.VariableString');
