<?php
/**
 * Generated by Haxe 4.1.5
 */

use \php\Boot;
use \haxe\Exception as HaxeException;

/**
 * The EReg class represents regular expressions.
 * While basic usage and patterns consistently work across platforms, some more
 * complex operations may yield different results. This is a necessary trade-
 * off to retain a certain level of performance.
 * EReg instances can be created by calling the constructor, or with the
 * special syntax `~/pattern/modifier`
 * EReg instances maintain an internal state, which is affected by several of
 * its methods.
 * A detailed explanation of the supported operations is available at
 * <https://haxe.org/manual/std-regex.html>
 */
final class EReg {
	/**
	 * @var bool
	 */
	public $global;
	/**
	 * @var string
	 */
	public $last;
	/**
	 * @var mixed
	 */
	public $matches;
	/**
	 * @var string
	 */
	public $options;
	/**
	 * @var string
	 */
	public $pattern;
	/**
	 * @var string
	 */
	public $re;

	/**
	 * Creates a new regular expression with pattern `r` and modifiers `opt`.
	 * This is equivalent to the shorthand syntax `~/r/opt`
	 * If `r` or `opt` are null, the result is unspecified.
	 * 
	 * @param string $r
	 * @param string $opt
	 * 
	 * @return void
	 */
	public function __construct ($r, $opt) {
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:37: characters 3-19
		$this->pattern = $r;
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:38: characters 3-45
		$this->options = str_replace("g", "", $opt);
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:39: characters 3-26
		$this->global = $this->options !== $opt;
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:40: characters 3-49
		$this->options = str_replace("u", "", $this->options);
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:41: characters 3-68
		$this->re = "\"" . (str_replace("\"", "\\\"", $r)??'null') . "\"" . ($this->options??'null');
	}

	/**
	 * @return void
	 */
	public function handlePregError () {
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:63: characters 3-36
		$e = preg_last_error();
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:64: lines 64-72
		if ($e === PREG_INTERNAL_ERROR) {
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:65: characters 4-9
			throw HaxeException::thrown("EReg: internal PCRE error");
		} else if ($e === PREG_BACKTRACK_LIMIT_ERROR) {
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:67: characters 4-9
			throw HaxeException::thrown("EReg: backtrack limit");
		} else if ($e === PREG_RECURSION_LIMIT_ERROR) {
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:69: characters 4-9
			throw HaxeException::thrown("EReg: recursion limit");
		} else if ($e === PREG_JIT_STACKLIMIT_ERROR) {
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:71: characters 4-9
			throw HaxeException::thrown("failed due to limited JIT stack space");
		}
	}

	/**
	 * Tells if `this` regular expression matches String `s`.
	 * This method modifies the internal state.
	 * If `s` is `null`, the result is unspecified.
	 * 
	 * @param string $s
	 * 
	 * @return bool
	 */
	public function match ($s) {
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:45: characters 10-29
		$p = preg_match(($this->re . "u"), $s, $this->matches, PREG_OFFSET_CAPTURE, 0);
		if ($p === false) {
			$this->handlePregError();
			$p = preg_match($this->re, $s, $this->matches, PREG_OFFSET_CAPTURE);
		}
		if ($p > 0) {
			$this->last = $s;
		} else {
			$this->last = null;
		}
		return $p > 0;
	}

	/**
	 * Returns the matched sub-group `n` of `this` EReg.
	 * This method should only be called after `this.match` or
	 * `this.matchSub`, and then operates on the String of that operation.
	 * The index `n` corresponds to the n-th set of parentheses in the pattern
	 * of `this` EReg. If no such sub-group exists, the result is unspecified.
	 * If `n` equals 0, the whole matched substring is returned.
	 * 
	 * @param int $n
	 * 
	 * @return string
	 */
	public function matched ($n) {
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:81: lines 81-82
		if (($this->matches === null) || ($n < 0)) {
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:82: characters 4-9
			throw HaxeException::thrown("EReg::matched");
		}
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:85: lines 85-86
		if ($n >= count($this->matches)) {
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:86: characters 4-15
			return null;
		}
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:87: lines 87-88
		if ($this->matches[$n][1] < 0) {
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:88: characters 4-15
			return null;
		}
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:89: characters 3-23
		return $this->matches[$n][0];
	}

	/**
	 * Replaces the first substring of `s` which `this` EReg matches with `by`.
	 * If `this` EReg does not match any substring, the result is `s`.
	 * By default, this method replaces only the first matched substring. If
	 * the global g modifier is in place, all matched substrings are replaced.
	 * If `by` contains `$1` to `$9`, the digit corresponds to number of a
	 * matched sub-group and its value is used instead. If no such sub-group
	 * exists, the replacement is unspecified. The string `$$` becomes `$`.
	 * If `s` or `by` are null, the result is unspecified.
	 * 
	 * @param string $s
	 * @param string $by
	 * 
	 * @return string
	 */
	public function replace ($s, $by) {
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:137: characters 3-46
		$by = str_replace("\\\$", "\\\\\$", $by);
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:138: characters 3-43
		$by = str_replace("\$\$", "\\\$", $by);
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:139: lines 139-141
		if (!preg_match("/\\\\([^?].*?\\\\)/", $this->re)) {
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:140: characters 4-57
			$by = preg_replace("/\\\$(\\d+)/", "\\\$\\1", $by);
		}
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:142: characters 3-71
		$result = preg_replace(($this->re . "u"), $by, $s, ($this->global ? -1 : 1));
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:143: lines 143-146
		if ($result === null) {
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:144: characters 4-21
			$this->handlePregError();
			#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:145: characters 4-60
			$result = preg_replace($this->re, $by, $s, ($this->global ? -1 : 1));
		}
		#C:\haxeToolkit_415\haxe\std/php/_std/EReg.hx:147: characters 3-16
		return $result;
	}
}

Boot::registerClass(EReg::class, 'EReg');
